# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing_extensions import Literal, TypeAlias

__all__ = ["SupportedContentType"]

SupportedContentType: TypeAlias = Literal[
    "image/jpeg",
    "image/png",
    "image/gif",
    "image/heic",
    "image/heif",
    "image/tiff",
    "image/bmp",
    "image/svg+xml",
    "image/webp",
    "image/x-icon",
    "video/mp4",
    "video/quicktime",
    "video/mpeg",
    "video/mpeg2",
    "video/x-m4v",
    "video/x-msvideo",
    "video/3gpp",
    "audio/mpeg",
    "audio/mp3",
    "audio/x-m4a",
    "audio/mp4",
    "audio/x-caf",
    "audio/x-wav",
    "audio/x-aiff",
    "audio/aiff",
    "audio/aac",
    "audio/midi",
    "audio/amr",
    "application/pdf",
    "application/vnd.apple.pkpass",
    "text/plain",
    "text/markdown",
    "text/vcard",
    "text/rtf",
    "text/csv",
    "text/html",
    "text/calendar",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/x-iwork-pages-sffpages",
    "application/x-iwork-numbers-sffnumbers",
    "application/x-iwork-keynote-sffkey",
    "application/epub+zip",
    "text/xml",
    "application/json",
    "application/zip",
    "application/x-gzip",
]
